services:
  postgres:
    image: postgres:17-alpine
    restart: "no"  
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      # Superuser username/password
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - "01-postgres:/var/lib/postgresql/data"

volumes:
  01-postgres: